server:
  port: 8086

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5455/testdb
    username: postgres
    password: adil
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:rukiya2020rukiya@gmail.com}
    password: ${SMTP_APP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.luxtech.notification: DEBUG
