server:
  port: 8086

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/luxtech_notification?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: sarafallahi59@gmail.com
    password: hopmajzkftiygvzn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.luxtech.notification: DEBUG